apiVersion: v1
kind: Service
metadata:
  name: pokemon-ialonso-service
  namespace: demo-argocd-ialonso
  labels:
    app: pokemon-ialonso
spec:
  selector:
    app: pokemon-ialonso
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
