apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-ialonso
  namespace: demo-argocd-ialonso
spec:
  selector:
    matchLabels:
      app: pokemon-ialonso
  replicas: 2
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0    
  template:
    metadata:
      labels:
        app: pokemon-ialonso
        project: projectpokemon
    spec:
      containers:
      - name: pokemon-container
        image: 641026500518.dkr.ecr.eu-west-1.amazonaws.com/ialonso-pokemon:0.0.1
        ports:
        - containerPort: 80
